export const FETCH_ALBUMS_REQUEST = 'FETCH_ALBUMS_REQUEST';
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS';

export const FETCH_ALBUM_PHOTOS_REQUEST = 'FETCH_ALBUM_PHOTOS_REQUEST';
export const FETCH_ALBUM_PHOTOS_SUCCESS = 'FETCH_ALBUM_PHOTOS_SUCCESS';
